### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by wolfier74** [AtharvRedij/react-google-form-spammer#1]
![image](https://user-images.githubusercontent.com/74510253/116983485-774f7780-acca-11eb-82b9-e9714848c9f3.png)

![image](https://user-images.githubusercontent.com/74510253/116983489-79193b00-acca-11eb-8612-7336067ea6f2.png)

**Comment by wolfier74** [comment]
Btw is this hostable on Vercel? What should I set here?
![image](https://user-images.githubusercontent.com/74510253/116983533-846c6680-acca-11eb-9293-ab32ff289fe4.png)

**Comment by AtharvRedij** [comment]
This project works perfectly fine on localhost but has an issue related to CORS when you host it online. I had this exact same issue (CORS) when I tried to host the project online on GitHub pages. 

If you find the solution, let me know.
